debug: false

# "env" endpoint only works when ActuatorsConfig is updated.
# "env" endpoint exposes a lot of information and should be off be default.
management.endpoints.web.exposure.include: health, info, env, metrics, prometheus

# Option to show a lot of git-info.
# management.info.git.mode: full

spring.datasource.url: jdbc:h2:mem:testdb;database_to_lower=true;trace_level_system_out=1
spring.datasource.hikari.minimumIdle: 1
spring.datasource.hikari.maximumPoolSize: 2
spring.sql.init.platform: h2
spring.sql.init.mode: embedded

logging.level:
  com.github.fwi: debug
  com.github.fwi.sbtreeconf.AcReport: info
  org.springframework: info
  org.springframework.jdbc.datasource.init.ScriptUtils: info
  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: info
  org.springframework.web.servlet.handler.HandlerMappingIntrospector: error

icecream.access.users:
- name: reader
  password: reads
  roles:
  - read
- name: writer
  password: writes
  roles:
  - write
- name: operator
  password: operates
  roles:
  - read
  - write
  - delete
- name: manager
  password: manages
  roles:
  - manage

icecream.access.login:
  max-failed-attempts: 3
  # Duration, e.g. 10s, 5m, 3h
  max-failed-timeout: 10s
  blocked-timeout: 30s
