debug: false

spring.datasource.url: jdbc:h2:mem:testdb;database_to_lower=true;trace_level_system_out=1
spring.datasource.hikari.minimumIdle: 1
spring.datasource.hikari.maximumPoolSize: 2
spring.sql.init.platform: h2
spring.sql.init.mode: embedded

logging.level:
  org.springframework: info
  org.springframework.jdbc.datasource.init.ScriptUtils: info
  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: info
