spring.application.name: Spring Boot Tree Configuration with ice cream
spring.main.banner-mode: off
spring.sql.init.mode: never
spring.jpa.open-in-view: false

# stop Hibernate from dropping data
spring.jpa.hibernate.ddl-auto: none

# Disable auto-commit when using Hibernate for speeeed,
# see also https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
spring.datasource.hikari.auto-commit: false

# Spring should set property below automatically when auto-commit is off.
# hibernate.connection.provider_disables_autocommit: true

# management.endpoints.web.exposure.include: '*'
management.server.port: 8081
management.endpoints.web.exposure.include: health, info, env, metrics, prometheus

# Enable application-availability
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

# Set some value to return in info-endpoint
management.info.build.enabled: true
management.info.git.enabled: true
management.info.env.enabled: true
management.info.java.enabled: true
info.app-name: ${spring.application.name}
