spring.application.name: Spring Boot Tree Configuration with ice cream
spring.main.banner-mode: off

# Requires Java 21 & Spring Boot 3.2.
spring.threads.virtual.enabled: true

# Prevent app from exiting when all threads are virtual.
spring.main.keep-alive: true

spring.mvc.problemdetails.enabled: true
server.error.whitelabel.enabled: false

spring.sql.init.mode: never
spring.jpa.open-in-view: false

# stop Hibernate from dropping data
spring.jpa.hibernate.ddl-auto: none

# Disable auto-commit when using Hibernate for speeeed,
# see also https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
# and https://vladmihalcea.com/spring-transaction-connection-management/
spring.datasource.hikari.auto-commit: false

# Spring should set property below automatically when auto-commit is off.
# hibernate.connection.provider_disables_autocommit: true
# spring.jpa.properties.hibernate.connection.provider_disables_autocommit: true

# management.endpoints.web.exposure.include: '*'
management.server.port: 8081
management.endpoints.web.exposure.include: health, info, metrics, prometheus, httpexchanges
# If you need distribution buckets in http-request metrics:
# management.metrics.distribution.percentiles-histogram.http.server.requests: true

# Enable application-availability
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always
management.endpoint.health.show-components: always
management.health.liveness-state.enabled: true
management.health.readiness-state.enabled: true
management.health.db.enabled: true
management.health.ping.enabled: true

# Set some value to return in info-endpoint
management.info.build.enabled: true
management.info.git.enabled: true
management.info.env.enabled: true
management.info.java.enabled: true
management.info.os.enabled: true
info.app-name: ${spring.application.name}

icecream.access.login:
  max-failed-attempts: 3
  # Duration, e.g. 10s, 5m, 3h
  max-failed-timeout: 5m
  blocked-timeout: 30m
